name: Phase 3 - Full MLOps Pipeline (Test -> Train -> Infer)

on:
  push:
    branches:
      - inference_branch

jobs:

  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest


  train_model:

    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run training script
        run: python src/train.py
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model 
          path: model_train.pkl 


  run_inference:

    needs: train_model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model 
      - name: Run inference script
        run: python src/inference.py